version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./basic:/var/www/html
    networks:
      - yii2net

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./basic:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii2net
    depends_on:
      - php

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii2
      MYSQL_PASSWORD: yii2
    ports:
      - "3306:3306"
    networks:
      - yii2net

networks:
  yii2net:
